// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbpVHpbYSGv3EezhTCfeb6Ewkic-E3e6o',
    appId: '1:666339180406:web:9bfd10b3af6ee160c44457',
    messagingSenderId: '666339180406',
    projectId: 'messmaster-6bb5e',
    authDomain: 'messmaster-6bb5e.firebaseapp.com',
    storageBucket: 'messmaster-6bb5e.firebasestorage.app',
    measurementId: 'G-B1YLKDWS0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kmOohz61VOoO-bisjX3fUfRpeZxnE24',
    appId: '1:666339180406:android:63d4ff47d83ecd2cc44457',
    messagingSenderId: '666339180406',
    projectId: 'messmaster-6bb5e',
    storageBucket: 'messmaster-6bb5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmY0kJZAewCm4zgZHA-nrt_zP-uz0AQI4',
    appId: '1:666339180406:ios:667535e8ccc2f25bc44457',
    messagingSenderId: '666339180406',
    projectId: 'messmaster-6bb5e',
    storageBucket: 'messmaster-6bb5e.firebasestorage.app',
    iosBundleId: 'com.example.messMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmY0kJZAewCm4zgZHA-nrt_zP-uz0AQI4',
    appId: '1:666339180406:ios:667535e8ccc2f25bc44457',
    messagingSenderId: '666339180406',
    projectId: 'messmaster-6bb5e',
    storageBucket: 'messmaster-6bb5e.firebasestorage.app',
    iosBundleId: 'com.example.messMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbpVHpbYSGv3EezhTCfeb6Ewkic-E3e6o',
    appId: '1:666339180406:web:c3eb1348366b1346c44457',
    messagingSenderId: '666339180406',
    projectId: 'messmaster-6bb5e',
    authDomain: 'messmaster-6bb5e.firebaseapp.com',
    storageBucket: 'messmaster-6bb5e.firebasestorage.app',
    measurementId: 'G-YTFPWNPYRP',
  );
}
